[project]
authors = ["Peter Urban <peter.urban@ugent.be>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "ping"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.11.0, <3.13.0"
jupyterlab = ">=4.3.4,<5"
matplotlib = ">=3.10.0,<4"
ipympl = ">=0.9.6,<0.10"
nbmake = ">=1.5.4,<2"
numba = ">=0.60.0,<0.61"
ipyleaflet = ">=0.19.2,<0.20"

[pypi-dependencies]
jupyterlab-execute-time = ">=3.2.0, <4"
themachinethatgoesping = ">=0.28.1, <0.29"
