[tool.poetry]
name = "tutorial"
version = "0.28.0"
description = ""
authors = ["Peter Urban <peter.urban@ugent.be>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10, <3.13"
themachinethatgoesping = "0.28.1"
matplotlib = "3.10.0"
jupyterlab = "4.3.4"
ipympl = "0.9.6"
nbmake = "^1.5.4"
ipyleaflet = "^0.19.2"
numba = "^0.60" #setting this here makes sure that e.g. numpy version is set compatible by poetry
jupyterlab-execute-time = "^3.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
