#src: https://discourse.jupyter.org/t/how-to-reduce-mybinder-org-repository-startup-time/4956/2


name: Test notebooks
on: [push] # You may want to trigger this Action on other things than a push.
jobs:
  test_notebooks:
    name:  ${{matrix.os}} py${{matrix.python_version}}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
        python_version: ['3.11', '3.12', '3.13']

    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/setup-python@v3
      with:
        python-version: ${{matrix.python_version}}
        
    - name: checkout main repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        lfs: true

    - name: "install poetry"
      run: pip install poetry

    - name: "install dependencies (poetry)"
      run: poetry install

    - name: "run tests"
      run: poetry run python test_notebooks.py
  build:
    needs: test_notebooks
    runs-on: ubuntu-latest
    steps:

    - name: checkout files in repo
      uses: actions/checkout@master

    - name: update jupyter dependencies with repo2docker
      uses: machine-learning-apps/repo2docker-action@master
      with:
        DOCKER_USERNAME: themachinethatgoesping
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        MYBINDERORG_TAG: ${{ github.event.ref }}
        PUBLIC_REGISTRY_CHECK: true
        NO_PUSH: true
